//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SID.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A,C,D,E,F,H,I,J,K,L,M,P,G")]
        public string SMSMappings {
            get {
                return ((string)(this["SMSMappings"]));
            }
            set {
                this["SMSMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\installation schedule\\current install schedule.xlsx")]
        public string InstallScheduleLocation {
            get {
                return ((string)(this["InstallScheduleLocation"]));
            }
            set {
                this["InstallScheduleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SID\\TempFiles")]
        public string TempFileDirectory {
            get {
                return ((string)(this["TempFileDirectory"]));
            }
            set {
                this["TempFileDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A,K,I,AR,BG,AQ,BC")]
        public string InstallMappings {
            get {
                return ((string)(this["InstallMappings"]));
            }
            set {
                this["InstallMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8,200")]
        public string InstallRows {
            get {
                return ((string)(this["InstallRows"]));
            }
            set {
                this["InstallRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultItemStatus {
            get {
                return ((int)(this["DefaultItemStatus"]));
            }
            set {
                this["DefaultItemStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\Stock, budgets etc")]
        public string SMSRootPath {
            get {
                return ((string)(this["SMSRootPath"]));
            }
            set {
                this["SMSRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StockOrJob,JobItemID,Room,ProductType,Item,ProductCode,Description,Colour,Dimensi" +
            "ons,Quantity,UnitPrice,SOPID,SupplierID")]
        public string sqlPOItemsMapping {
            get {
                return ((string)(this["sqlPOItemsMapping"]));
            }
            set {
                this["sqlPOItemsMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O,SMSStatus;B,OtherInfo")]
        public string SMSAddColumns {
            get {
                return ((string)(this["SMSAddColumns"]));
            }
            set {
                this["SMSAddColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProductCode")]
        public string ImportFrozenColumn {
            get {
                return ((string)(this["ImportFrozenColumn"]));
            }
            set {
                this["ImportFrozenColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,100,100,100,100,100,100")]
        public string ImportColumnWidths {
            get {
                return ((string)(this["ImportColumnWidths"]));
            }
            set {
                this["ImportColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMSStatus,1;ItemStatusID,2;ProductType,3;ItemAreaID,4;SupplierID,5;SOPID,6;OtherI" +
            "nfo, 18;OrderEarly,19")]
        public string ImportColumnOrders {
            get {
                return ((string)(this["ImportColumnOrders"]));
            }
            set {
                this["ImportColumnOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MISC3")]
        public string DefaultSAGEID {
            get {
                return ((string)(this["DefaultSAGEID"]));
            }
            set {
                this["DefaultSAGEID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DefaultTaxCode {
            get {
                return ((string)(this["DefaultTaxCode"]));
            }
            set {
                this["DefaultTaxCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41100")]
        public string DefaultNominal {
            get {
                return ((string)(this["DefaultNominal"]));
            }
            set {
                this["DefaultNominal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOPID,InstallID,InstallDate,OriginalInstallDate,RAG,InstallNumber,OpsDate")]
        public string SqlInstallMappings {
            get {
                return ((string)(this["SqlInstallMappings"]));
            }
            set {
                this["SqlInstallMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string InstallSheetNumber {
            get {
                return ((string)(this["InstallSheetNumber"]));
            }
            set {
                this["InstallSheetNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoImportInstall {
            get {
                return ((bool)(this["AutoImportInstall"]));
            }
            set {
                this["AutoImportInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string SiteAddressColumn {
            get {
                return ((string)(this["SiteAddressColumn"]));
            }
            set {
                this["SiteAddressColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Show Business Interiors,Unit 1 Millbuck Way,Moston Road,Sandbach,Cheshire,CW11 3G" +
            "Q")]
        public string ShowbizAddress {
            get {
                return ((string)(this["ShowbizAddress"]));
            }
            set {
                this["ShowbizAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\sapos\\pdf")]
        public string DocuwareSaveLocation {
            get {
                return ((string)(this["DocuwareSaveLocation"]));
            }
            set {
                this["DocuwareSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\sapos\\csv")]
        public string AdeptSaveLocation {
            get {
                return ((string)(this["AdeptSaveLocation"]));
            }
            set {
                this["AdeptSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string POColumnWidths {
            get {
                return ((string)(this["POColumnWidths"]));
            }
            set {
                this["POColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string POColumnOrders {
            get {
                return ((string)(this["POColumnOrders"]));
            }
            set {
                this["POColumnOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOPID")]
        public string POFrozenColumn {
            get {
                return ((string)(this["POFrozenColumn"]));
            }
            set {
                this["POFrozenColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51100")]
        public int CarriageNominal {
            get {
                return ((int)(this["CarriageNominal"]));
            }
            set {
                this["CarriageNominal"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SBI-SRV-04\\SQLEXPRESS;Initial Catalog=POTEST;Integrated Security=True" +
            "")]
        public string POTESTConnectionString {
            get {
                return ((string)(this["POTESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SBI-SRV-04\\SQLEXPRESS;Initial Catalog=sbi_salesdb;Integrated Security" +
            "=True")]
        public string sbi_salesdbConnectionString {
            get {
                return ((string)(this["sbi_salesdbConnectionString"]));
            }
        }
    }
}
